# 1 定义
## 1.1 tensor张量
### 1.1.1 PyTorch的tensor与NumPy array相互转换
PyTorch的很多操作和numpy都是类似的，但是因为其能够在 GPU 上运行，所以比 NumPy 快很多。

In [8]:
import torch
import numpy as np
# 创建一个 numpy ndarray
numpy_tensor = np.random.randn(10, 20)
x = torch.randn(10, 20)

ndarray==>tensor
- torch.Tensor 强制类型转换
- torch.from_numpy创建函数

In [2]:
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)
print(type(pytorch_tensor2))
print(type(pytorch_tensor1))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


tensor==>ndarray

In [3]:
# 如果 pytorch tensor 在 cpu 上
numpy_array = pytorch_tensor1.numpy()

# 如果 pytorch tensor 在 gpu 上
numpy_array = pytorch_tensor1.cpu().numpy()

### 1.1.2 PyTorch Tensor 使用 GPU 加速
- CPU==>GPU

In [ ]:
# 第一种方式是定义 cuda 数据类型
dtype = torch.cuda.FloatTensor # 定义默认 GPU 的 数据类型
gpu_tensor = torch.randn(10, 20).type(dtype)

# 第二种方式更简单，推荐使用
gpu_tensor = torch.randn(10, 20).cuda() # 将 tensor 放在GPU 上

### 1.1.3 tensor的属性

In [4]:
# 可以通过下面两种方式得到 tensor 的大小
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())

torch.Size([10, 20])
torch.Size([10, 20])


In [5]:
# 得到 tensor 的数据类型
print(pytorch_tensor1.type())

torch.FloatTensor


In [6]:
# 得到 tensor 的维度
print(pytorch_tensor1.dim())

2


In [7]:
# 得到 tensor 的所有元素个数
print(pytorch_tensor1.numel())

200


### 1.1. 4 tensor的数据类型变换

In [9]:
x = torch.randn(3, 2)
print(x)
x = x.type(torch.DoubleTensor)
print(x)
x_array = x.numpy()
print(x_array.dtype)

tensor([[ 0.7193, -0.1279],
        [ 1.1413, -1.7994],
        [ 0.5069,  1.6252]])
tensor([[ 0.7193, -0.1279],
        [ 1.1413, -1.7994],
        [ 0.5069,  1.6252]], dtype=torch.float64)
float64


## 1.2 tensor的操作

### 1.2.1 squeeze和unsqueeze操作: 降维升维
增加维度,特征长度为1

In [15]:
print(torch.ones(2, 2))
print(torch.ones(2, 2).size())
print(torch.ones(2, 2).type())
x = torch.ones(2, 2).unsqueeze(0)
print(x) # 这是一个float tensor
print(x.size())
print(x.type()) # 打印类型

x = x.squeeze() # 将 tensor 中所有的一维全部都去掉
print(x.shape)

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
torch.FloatTensor
tensor([[[1., 1.],
         [1., 1.]]])
torch.Size([1, 2, 2])
torch.FloatTensor
torch.Size([2, 2])


### 1.2.2 数值类型转换

In [14]:
# 将其转化为整形
x = x.long()
# x = x.type(torch.LongTensor)
print(x.type())

torch.LongTensor


### 1.2.4 使用permute和transpose进行维度交换

In [16]:
x = torch.randn(3, 4, 5)
print(x.shape)

# 使用permute和transpose进行维度交换
x = x.permute(1, 0, 2) # permute 可以重新排列 tensor 的维度
print(x.shape)

x = x.transpose(0, 2)  # transpose 交换 tensor 中的两个维度
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


### 1.2.5 使用 view 对 tensor 进行 reshape

In [17]:
x = torch.randn(3, 4, 5)
print(x.shape)

## 拉伸
x = x.view(-1, 5) # -1 表示任意的大小，5 表示第二维变成 5
print(x.shape)

x = x.view(3, 20) # 重新 reshape 成 (3, 20) 的大小
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


### 1.2.6 tensor的相加

In [21]:
x = torch.zeros(3, 4)
y = torch.ones(3, 4)

# 两个 tensor 求和
z = x + y
print(z)
z = torch.add(x, y)
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## 1.3 inplace操作
pytorch中大多数的操作都支持 inplace 操作，也就是可以直接对 tensor 进行操作而不需要另外开辟内存空间。方式非常简单，一般都是在操作的符号后面加_

## 1.4 变量Variable

- from torch.autograd import Variable
- Variable 是对 tensor 的封装，操作和 tensor 是一样的，
- 但是每个 Variabel都有三个属性，Variable 中的`.data`，梯度`.grad`以及这个 Variable 是通过什么方式得到的`.grad_fn`。

### 1.4.1 关于梯队

In [23]:
# 通过下面这种方式导入 Variable
from torch.autograd import Variable
x_tensor = torch.randn(10, 5)
y_tensor = torch.randn(10, 5)

# 将 tensor 变成 Variable
x = Variable(x_tensor, requires_grad=True) # 默认 Variable 是不需要求梯度的，所以我们用这个方式申明需要对其进行求梯度